# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cheapshot < Formula
  desc "CLI for LLM batch APIs. Chain multi-step workflows with Unix pipes."
  homepage "https://github.com/prototypeasap/cheapshot"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.1/cheapshot_darwin_amd64.tar.gz"
      sha256 "d06e5daaec9f551af94c9a02bd8aad7d7b78ffbe3061feb9d1b532378aacd2a7"

      define_method(:install) do
        bin.install "cheapshot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.1/cheapshot_darwin_arm64.tar.gz"
      sha256 "32a2639b0d6f54449cada8958bb36bdee7cb0f2e1fd0a118c8ec2a4a07853ad9"

      define_method(:install) do
        bin.install "cheapshot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.1/cheapshot_linux_amd64.tar.gz"
      sha256 "5de6697455d4d003b6d7fa9fad959a3d240091df43ee902697ffb41ff5ba8615"
      define_method(:install) do
        bin.install "cheapshot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.1/cheapshot_linux_arm64.tar.gz"
      sha256 "2c48f23c26c50997fa681f174234e3260fe41c2b41babe28a94818acad86c819"
      define_method(:install) do
        bin.install "cheapshot"
      end
    end
  end

  test do
    system bin/"cheapshot", "--version"
  end
end
