# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cheapshot < Formula
  desc "CLI for LLM batch APIs. Chain multi-step workflows with Unix pipes."
  homepage "https://github.com/prototypeasap/cheapshot"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.0/cheapshot_darwin_amd64.tar.gz"
      sha256 "0e98703e24be70e5ded285a231fa10381c188f081e207936e593963d8030db1c"

      define_method(:install) do
        bin.install "cheapshot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.0/cheapshot_darwin_arm64.tar.gz"
      sha256 "06eb4ca4e149580a0534ec10198b9e25722c0ac0abcab35908d63494386c8714"

      define_method(:install) do
        bin.install "cheapshot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.0/cheapshot_linux_amd64.tar.gz"
      sha256 "91d6909e86f2746911e023d4ae0e88d599462a666e9fb9afaa52b4157fc2eaaf"
      define_method(:install) do
        bin.install "cheapshot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.0/cheapshot_linux_arm64.tar.gz"
      sha256 "e69e0732ba7191b384d5b725f77c7e40616d4e021b53856cc096ff61cbb47f25"
      define_method(:install) do
        bin.install "cheapshot"
      end
    end
  end

  test do
    system bin/"cheapshot", "--version"
  end
end
