# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cheapshot < Formula
  desc "CLI for LLM batch APIs. Chain multi-step workflows with Unix pipes."
  homepage "https://github.com/prototypeasap/cheapshot"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.0/cheapshot_darwin_amd64.tar.gz"
      sha256 "0bb25d4bbf4314e6dfc786126c998ccd4e9e7d39178d871f1bf2ebaabea5542f"

      define_method(:install) do
        bin.install "cheapshot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.0/cheapshot_darwin_arm64.tar.gz"
      sha256 "4c1a1bd6d5bf72e9eaf7819f4865ac64cc1eecd607a8a2772857881e9c2d11c0"

      define_method(:install) do
        bin.install "cheapshot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.0/cheapshot_linux_amd64.tar.gz"
      sha256 "227dfcf2eb6ae5495140f3c5fc936b013fc526e14ead09a54a7e2038d829596d"
      define_method(:install) do
        bin.install "cheapshot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prototypeasap/cheapshot/releases/download/v0.2.0/cheapshot_linux_arm64.tar.gz"
      sha256 "77eccf4b8601c4c48aa2acc00efd7e9134e43458dee35e9a8e11670644a81aa7"
      define_method(:install) do
        bin.install "cheapshot"
      end
    end
  end

  test do
    system bin/"cheapshot", "--version"
  end
end
